# this file is needed to install the package from git without support for subdirectories
# see: https://github.com/python-poetry/poetry/issues/755

[tool.poetry]
name = "kilroyplot"
version = "0.2.4"
description = "kilroy plot styling 📊"
readme = "kilroyplot/README.md"
authors = ["kilroy <kilroymail@pm.me>"]
classifiers = ["License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]
repository = "https://github.com/kilroybot/kilroyplot"
packages = [{ include = "kilroyplot", from = "kilroyplot/src" }]

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.5"
appdirs = "^1.4"
diskcache = "^5.4"

# dev
jupyterlab = { version = "^3.2", optional = true }

# test
pytest = { version = "^7.0", optional = true }

[tool.poetry.extras]
# need to do it that way until poetry supports dependency groups: https://github.com/python-poetry/poetry/issues/1644
dev = ["jupyterlab", "pytest"]
test = ["pytest"]

[build-system]
# this should be there, see https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
